branch-defaults:
  master:
    environment: products-node-dev
    group_suffix: null
global:
  application_name: products-node-dev
  default_ec2_keyname: magoo-note
  default_platform: Node.js
  default_region: sa-east-1
  profile: eb-cli
  sc: git
